---
version: 2
executorType: docker
containerInfo:
  - image: dickeyxxx/cli-engine@sha256:4b54ba455ea8d9675b4dc501e874d83a1f6c0bf0aee7427ee55217e2de1d150e
stages:
  build:
    workDir: ~/cli
    steps:
      - type: checkout
      - type: cache-restore
        key: cli
      - type: shell
        command: |
          set -exu
          yarn
          ./bin/run version
          ./bin/run help
      - type: cache-save
        key: cli
        paths:
          - /usr/local/share/.cache/yarn
      - type: deploy
        shell: /bin/bash
        command: |
          set -exu
          if [ "${CIRCLE_BRANCH}" == "v6" ]; then
            yarn run release beta
          fi
